pkgRoot: dist/ngx-jira-issue-collector
branches: 
  - "8.x"
  - master
tagFormat: "${version}"
preset: "angular"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/changelog"
  - "@semantic-release/release-notes-generator"
  - semantic-release-ado
